FROM ocaml/opam2

RUN echo build from here .......

# some of the following apt packages are likely already installed
RUN sudo apt-get install -y git make
RUN sudo apt-get install -y curl
RUN sudo apt-get install -y gcc
RUN sudo apt-get install -y bzip2
RUN sudo apt-get install -y wget
RUN sudo apt-get install -y unzip m4
RUN sudo apt-get install -y time
RUN sudo apt-get install -y rsync bubblewrap

RUN opam install -y dune ocamlfind odoc
RUN opam pin add -y -n tjr_lib_core https://github.com/tomjridge/tjr_lib.git
RUN opam pin add -y -n tjr_lib https://github.com/tomjridge/tjr_lib.git
RUN opam pin add -y -n tjr_fs_shared https://github.com/tomjridge/tjr_fs_shared.git
RUN opam pin add -y -n tjr_monad https://github.com/tomjridge/tjr_monad.git
RUN opam pin add -y -n tjr_profile https://github.com/tomjridge/tjr_profile.git
RUN opam pin add -y -n isa_btree https://github.com/tomjridge/isa_btree.git
RUN opam pin add -y -n tjr_btree https://github.com/tomjridge/tjr_btree.git#dev
RUN opam pin add -y -n tjr_btree_examples https://github.com/tomjridge/tjr_btree.git#dev
RUN opam install -y tjr_btree_examples
