DUNE:=dune

run_examples:
	$(DUNE) exec examples/int_int_map_example_functionality.exe
	$(DUNE) exec examples/string_string_map_example_functionality.exe
	./exercise_ii_map.sh  # FIXME note startup time seems a bit long for the .exe
	./exercise_ss_map.sh

test_startup_time:
	time for f in `seq 1 100`; do ./int_int_map_main.exe nop; done
	echo Total time is about 1.7 s, or .017s per run


clean:
	rm -f btree.store


